# TCL File Generated by Component Editor 16.1
# Tue Jul 25 19:03:06 CEST 2017
# DO NOT MODIFY


# 
# hd6309_avalon_master "hd6309_avalon_master" v0.1.1
# Marek Materzok 2017.07.25.19:03:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hd6309_avalon_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME hd6309_avalon_master
set_module_property VERSION 0.1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP private
set_module_property AUTHOR "Marek Materzok"
set_module_property DISPLAY_NAME hd6309_avalon_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hd6309_avalon_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hd6309_avalon_master.v VERILOG PATH hd6309_avalon_master.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hd6309_avalon_master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file hd6309_avalon_master.v VERILOG PATH hd6309_avalon_master.v


# 
# parameters
# 
add_parameter WIDTH INTEGER 16
set_parameter_property WIDTH DEFAULT_VALUE 16
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point bus
# 
add_interface bus conduit end
set_interface_property bus associatedClock clock
set_interface_property bus associatedReset reset
set_interface_property bus ENABLED true
set_interface_property bus EXPORT_OF ""
set_interface_property bus PORT_NAME_MAP ""
set_interface_property bus CMSIS_SVD_VARIABLES ""
set_interface_property bus SVD_ADDRESS_GROUP ""

add_interface_port bus bus_address address Input WIDTH
add_interface_port bus bus_data_in data_in Output 8
add_interface_port bus bus_data_out data_out Input 8
add_interface_port bus bus_e e Input 1
add_interface_port bus bus_mrdy mrdy Output 1
add_interface_port bus bus_q q Input 1
add_interface_port bus bus_rw rw Input 1
add_interface_port bus bus_ba ba Input 1
add_interface_port bus bus_bs bs Input 1
add_interface_port bus bus_reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output WIDTH
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_readdata readdata Input 8
add_interface_port avalon_master master_writedata writedata Output 8
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_response response Input 2
add_interface_port avalon_master master_writeresponsevalid writeresponsevalid Input 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1

